name: 需求建议
description: 新功能、建议等
labels: ["enhancement"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: 确保理解以下内容后再开始填写 issue
      options:
        - label: 我知道 issue 是用于反馈和解决问题的，而非吐槽评论区
          required: true
        - label: issue 标题简洁明了，概括问题大纲
          required: true
        - label: 我基本确定我需要一个新功能，而不是遇到了 bug (不确定的话请附上日志)
          required: true
        - label: 我使用的是最新版本，开发者不会也不应该解决旧版本发生的问题
          required: true
        - label: 我已使用搜索功能确认了没有其他 issue、pr、讨论、release 等 (包括已关闭的 issue、pr) 提及过本问题，如果有重复问题，应当在对应的位置发布，而不是新建 issue
          required: true

  - type: textarea
    id: describe
    attributes:
      label: 需求描述
      description: |
        从需求角度出发，描述新功能能解决什么需求
        如果功能复杂，最好附带该功能的展示图 (可以让 AI 生成图像) 
        *按粘贴键可以直接粘贴图像*
    validations:
      required: false
