import enum
from dataclasses import dataclass


class Win_virtual_key(enum.Enum):
    @dataclass(slots=True, frozen=True)
    class Value:
        code: int
        desc: str

    VK_LBUTTON = Value(0x01, "Left mouse button")
    VK_RBUTTON = Value(0x02, "Right mouse button")
    VK_CANCEL = Value(0x03, "Control-break processing")
    VK_MBUTTON = Value(0x04, "Middle mouse button")
    VK_XBUTTON1 = Value(0x05, "X1 mouse button")
    VK_XBUTTON2 = Value(0x06, "X2 mouse button")
    VK_BACK = Value(0x08, "Backspace key")
    VK_TAB = Value(0x09, "Tab key")
    VK_CLEAR = Value(0x0C, "Clear key")
    VK_RETURN = Value(0x0D, "Enter key")
    VK_SHIFT = Value(0x10, "Shift key")
    VK_CONTROL = Value(0x11, "Ctrl key")
    VK_MENU = Value(0x12, "Alt key")
    VK_PAUSE = Value(0x13, "Pause key")
    VK_CAPITAL = Value(0x14, "Caps lock key")
    VK_KANA = Value(0x15, "IME Kana mode")
    VK_HANGUL = Value(0x15, "IME Hangul mode")
    VK_IME_ON = Value(0x16, "IME On")
    VK_JUNJA = Value(0x17, "IME Junja mode")
    VK_FINAL = Value(0x18, "IME final mode")
    VK_HANJA = Value(0x19, "IME Hanja mode")
    VK_KANJI = Value(0x19, "IME Kanji mode")
    VK_IME_OFF = Value(0x1A, "IME Off")
    VK_ESCAPE = Value(0x1B, "Esc key")
    VK_CONVERT = Value(0x1C, "IME convert")
    VK_NONCONVERT = Value(0x1D, "IME nonconvert")
    VK_ACCEPT = Value(0x1E, "IME accept")
    VK_MODECHANGE = Value(0x1F, "IME mode change request")
    VK_SPACE = Value(0x20, "Spacebar key")
    VK_PRIOR = Value(0x21, "Page up key")
    VK_NEXT = Value(0x22, "Page down key")
    VK_END = Value(0x23, "End key")
    VK_HOME = Value(0x24, "Home key")
    VK_LEFT = Value(0x25, "Left arrow key")
    VK_UP = Value(0x26, "Up arrow key")
    VK_RIGHT = Value(0x27, "Right arrow key")
    VK_DOWN = Value(0x28, "Down arrow key")
    VK_SELECT = Value(0x29, "Select key")
    VK_PRINT = Value(0x2A, "Print key")
    VK_EXECUTE = Value(0x2B, "Execute key")
    VK_SNAPSHOT = Value(0x2C, "Print screen key")
    VK_INSERT = Value(0x2D, "Insert key")
    VK_DELETE = Value(0x2E, "Delete key")
    VK_HELP = Value(0x2F, "Help key")
    _0 = Value(0x30, "0 key")
    _1 = Value(0x31, "1 key")
    _2 = Value(0x32, "2 key")
    _3 = Value(0x33, "3 key")
    _4 = Value(0x34, "4 key")
    _5 = Value(0x35, "5 key")
    _6 = Value(0x36, "6 key")
    _7 = Value(0x37, "7 key")
    _8 = Value(0x38, "8 key")
    _9 = Value(0x39, "9 key")
    A = Value(0x41, "A key")
    B = Value(0x42, "B key")
    C = Value(0x43, "C key")
    D = Value(0x44, "D key")
    E = Value(0x45, "E key")
    F = Value(0x46, "F key")
    G = Value(0x47, "G key")
    H = Value(0x48, "H key")
    I = Value(0x49, "I key")  # noqa: E741
    J = Value(0x4A, "J key")
    K = Value(0x4B, "K key")
    L = Value(0x4C, "L key")
    M = Value(0x4D, "M key")
    N = Value(0x4E, "N key")
    O = Value(0x4F, "O key")  # noqa: E741
    P = Value(0x50, "P key")
    Q = Value(0x51, "Q key")
    R = Value(0x52, "R key")
    S = Value(0x53, "S key")
    T = Value(0x54, "T key")
    U = Value(0x55, "U key")
    V = Value(0x56, "V key")
    W = Value(0x57, "W key")
    X = Value(0x58, "X key")
    Y = Value(0x59, "Y key")
    Z = Value(0x5A, "Z key")
    VK_LWIN = Value(0x5B, "Left Windows logo key")
    VK_RWIN = Value(0x5C, "Right Windows logo key")
    VK_APPS = Value(0x5D, "Application key")
    VK_SLEEP = Value(0x5F, "Computer Sleep key")
    VK_NUMPAD0 = Value(0x60, "Numeric keypad 0 key")
    VK_NUMPAD1 = Value(0x61, "Numeric keypad 1 key")
    VK_NUMPAD2 = Value(0x62, "Numeric keypad 2 key")
    VK_NUMPAD3 = Value(0x63, "Numeric keypad 3 key")
    VK_NUMPAD4 = Value(0x64, "Numeric keypad 4 key")
    VK_NUMPAD5 = Value(0x65, "Numeric keypad 5 key")
    VK_NUMPAD6 = Value(0x66, "Numeric keypad 6 key")
    VK_NUMPAD7 = Value(0x67, "Numeric keypad 7 key")
    VK_NUMPAD8 = Value(0x68, "Numeric keypad 8 key")
    VK_NUMPAD9 = Value(0x69, "Numeric keypad 9 key")
    VK_MULTIPLY = Value(0x6A, "Multiply key")
    VK_ADD = Value(0x6B, "Add key")
    VK_SEPARATOR = Value(0x6C, "Separator key")
    VK_SUBTRACT = Value(0x6D, "Subtract key")
    VK_DECIMAL = Value(0x6E, "Decimal key")
    VK_DIVIDE = Value(0x6F, "Divide key")
    VK_F1 = Value(0x70, "F1 key")
    VK_F2 = Value(0x71, "F2 key")
    VK_F3 = Value(0x72, "F3 key")
    VK_F4 = Value(0x73, "F4 key")
    VK_F5 = Value(0x74, "F5 key")
    VK_F6 = Value(0x75, "F6 key")
    VK_F7 = Value(0x76, "F7 key")
    VK_F8 = Value(0x77, "F8 key")
    VK_F9 = Value(0x78, "F9 key")
    VK_F10 = Value(0x79, "F10 key")
    VK_F11 = Value(0x7A, "F11 key")
    VK_F12 = Value(0x7B, "F12 key")
    VK_F13 = Value(0x7C, "F13 key")
    VK_F14 = Value(0x7D, "F14 key")
    VK_F15 = Value(0x7E, "F15 key")
    VK_F16 = Value(0x7F, "F16 key")
    VK_F17 = Value(0x80, "F17 key")
    VK_F18 = Value(0x81, "F18 key")
    VK_F19 = Value(0x82, "F19 key")
    VK_F20 = Value(0x83, "F20 key")
    VK_F21 = Value(0x84, "F21 key")
    VK_F22 = Value(0x85, "F22 key")
    VK_F23 = Value(0x86, "F23 key")
    VK_F24 = Value(0x87, "F24 key")
    VK_NUMLOCK = Value(0x90, "Num lock key")
    VK_SCROLL = Value(0x91, "Scroll lock key")
    VK_LSHIFT = Value(0xA0, "Left Shift key")
    VK_RSHIFT = Value(0xA1, "Right Shift key")
    VK_LCONTROL = Value(0xA2, "Left Ctrl key")
    VK_RCONTROL = Value(0xA3, "Right Ctrl key")
    VK_LMENU = Value(0xA4, "Left Alt key")
    VK_RMENU = Value(0xA5, "Right Alt key")
    VK_BROWSER_BACK = Value(0xA6, "Browser Back key")
    VK_BROWSER_FORWARD = Value(0xA7, "Browser Forward key")
    VK_BROWSER_REFRESH = Value(0xA8, "Browser Refresh key")
    VK_BROWSER_STOP = Value(0xA9, "Browser Stop key")
    VK_BROWSER_SEARCH = Value(0xAA, "Browser Search key")
    VK_BROWSER_FAVORITES = Value(0xAB, "Browser Favorites key")
    VK_BROWSER_HOME = Value(0xAC, "Browser Start and Home key")
    VK_VOLUME_MUTE = Value(0xAD, "Volume Mute key")
    VK_VOLUME_DOWN = Value(0xAE, "Volume Down key")
    VK_VOLUME_UP = Value(0xAF, "Volume Up key")
    VK_MEDIA_NEXT_TRACK = Value(0xB0, "Next Track key")
    VK_MEDIA_PREV_TRACK = Value(0xB1, "Previous Track key")
    VK_MEDIA_STOP = Value(0xB2, "Stop Media key")
    VK_MEDIA_PLAY_PAUSE = Value(0xB3, "Play/Pause Media key")
    VK_LAUNCH_MAIL = Value(0xB4, "Start Mail key")
    VK_LAUNCH_MEDIA_SELECT = Value(0xB5, "Select Media key")
    VK_LAUNCH_APP1 = Value(0xB6, "Start Application 1 key")
    VK_LAUNCH_APP2 = Value(0xB7, "Start Application 2 key")
    VK_OEM_1 = Value(
        0xBA,
        "It can vary by keyboard. For the US ANSI keyboard , the Semicolon and Colon key",
    )
    VK_OEM_PLUS = Value(0xBB, "For any country/region, the Equals and Plus key")
    VK_OEM_COMMA = Value(0xBC, "For any country/region, the Comma and Less Than key")
    VK_OEM_MINUS = Value(0xBD, "For any country/region, the Dash and Underscore key")
    VK_OEM_PERIOD = Value(
        0xBE, "For any country/region, the Period and Greater Than key"
    )
    VK_OEM_2 = Value(
        0xBF,
        "It can vary by keyboard. For the US ANSI keyboard, the Forward Slash and Question Mark key",
    )
    VK_OEM_3 = Value(
        0xC0,
        "It can vary by keyboard. For the US ANSI keyboard, the Grave Accent and Tilde key",
    )
    VK_GAMEPAD_A = Value(0xC3, "Gamepad A button")
    VK_GAMEPAD_B = Value(0xC4, "Gamepad B button")
    VK_GAMEPAD_X = Value(0xC5, "Gamepad X button")
    VK_GAMEPAD_Y = Value(0xC6, "Gamepad Y button")
    VK_GAMEPAD_RIGHT_SHOULDER = Value(0xC7, "Gamepad Right Shoulder button")
    VK_GAMEPAD_LEFT_SHOULDER = Value(0xC8, "Gamepad Left Shoulder button")
    VK_GAMEPAD_LEFT_TRIGGER = Value(0xC9, "Gamepad Left Trigger button")
    VK_GAMEPAD_RIGHT_TRIGGER = Value(0xCA, "Gamepad Right Trigger button")
    VK_GAMEPAD_DPAD_UP = Value(0xCB, "Gamepad D-pad Up button")
    VK_GAMEPAD_DPAD_DOWN = Value(0xCC, "Gamepad D-pad Down button")
    VK_GAMEPAD_DPAD_LEFT = Value(0xCD, "Gamepad D-pad Left button")
    VK_GAMEPAD_DPAD_RIGHT = Value(0xCE, "Gamepad D-pad Right button")
    VK_GAMEPAD_MENU = Value(0xCF, "Gamepad Menu/Start button")
    VK_GAMEPAD_VIEW = Value(0xD0, "Gamepad View/Back button")
    VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON = Value(0xD1, "Gamepad Left Thumbstick button")
    VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON = Value(0xD2, "Gamepad Right Thumbstick button")
    VK_GAMEPAD_LEFT_THUMBSTICK_UP = Value(0xD3, "Gamepad Left Thumbstick up")
    VK_GAMEPAD_LEFT_THUMBSTICK_DOWN = Value(0xD4, "Gamepad Left Thumbstick down")
    VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT = Value(0xD5, "Gamepad Left Thumbstick right")
    VK_GAMEPAD_LEFT_THUMBSTICK_LEFT = Value(0xD6, "Gamepad Left Thumbstick left")
    VK_GAMEPAD_RIGHT_THUMBSTICK_UP = Value(0xD7, "Gamepad Right Thumbstick up")
    VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN = Value(0xD8, "Gamepad Right Thumbstick down")
    VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT = Value(0xD9, "Gamepad Right Thumbstick right")
    VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT = Value(0xDA, "Gamepad Right Thumbstick left")
    VK_OEM_4 = Value(
        0xDB,
        "It can vary by keyboard. For the US ANSI keyboard, the Left Brace key",
    )
    VK_OEM_5 = Value(
        0xDC,
        "It can vary by keyboard. For the US ANSI keyboard, the Backslash and Pipe key",
    )
    VK_OEM_6 = Value(
        0xDD,
        "It can vary by keyboard. For the US ANSI keyboard, the Right Brace key",
    )
    VK_OEM_7 = Value(
        0xDE,
        "It can vary by keyboard. For the US ANSI keyboard, the Apostrophe and Double Quotation Mark key",
    )
    VK_OEM_8 = Value(
        0xDF,
        "It can vary by keyboard. For the Canadian CSA keyboard, the Right Ctrl key",
    )
    VK_OEM_102 = Value(
        0xE2,
        "It can vary by keyboard. For the European ISO keyboard, the Backslash and Pipe key",
    )
    VK_PROCESSKEY = Value(0xE5, "IME PROCESS key")
    VK_PACKET = Value(
        0xE7,
        'Used to pass Unicode characters as if they were keystrokes. The VK_PACKET key is the low word of a 32-bit Virtual Key value used for non-keyboard input methods. For mor"e information, see Remark in" [KEYBDINPUT]Value(/en-us/windows/win32/api/winuser/ns-winuser-keybdinput), [SendInput]Value(/en-us/windows/win32/api/winuser/nf-winuser-sendinput), [WM_KEYDOW"N]Value(wm-keydown), and [WM_KEYUP]Value(wm"-keyup)',
    )
    VK_ATTN = Value(0xF6, "Attn key")
    VK_CRSEL = Value(0xF7, "CrSel key")
    VK_EXSEL = Value(0xF8, "ExSel key")
    VK_EREOF = Value(0xF9, "Erase EOF key")
    VK_PLAY = Value(0xFA, "Play key")
    VK_ZOOM = Value(0xFB, "Zoom key")
    VK_NONAME = Value(0xFC, "Reserved")
    VK_PA1 = Value(0xFD, "PA1 key")
    VK_OEM_CLEAR = Value(0xFE, "Clear key")
